version: '3'
service:
  httpd_service:
    image: 'httpd'
    ports: 
     - '80-83:80'
    volumes: '/mnt/index:/usr/local/apache2/htdocs/'

  tomcat_service:
    image: 'tomcat:9'
    ports:
     - '8081-80803:8080'
    volumes: '/mnt/project/game-of-life/gameoflife-web/target/gameoflife.war:/usr/local/tomcat/webapps/'   
